### PR TITLE
Updated Dinner Notes

### PR DESCRIPTION
**Pull request by ellaberkeley**
Dinner recipe description

## 🎯 Objective

_Note why you're making this change and any relevant issues_

## 🛠️ Changes made

_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by halyreza2** [comment]
Good dinner notes.

**Review by tzsidhu — APPROVED** [review]
👍

**Review by solelibedinskyale — APPROVED** [review]
I like it

**Review by halyreza2 — COMMENTED** [review]
Great description

**Pull request merged**
